[package]
name = "day21"
version = "0.1.0"
authors = ["Mikael Zayenz Lagerkvist <zayenz@gmail.com>"]

[dependencies]
failure = "0.1.1"
strum = "0.8.0"
strum_macros = "0.8.0"
rayon = "0.9.0"
aoc2017 = { path = "../aoc2017"}


[dev-dependencies]
assert_cli = "0.5"
