[package]
name = "day16-2"
version = "0.1.0"
authors = ["Mikael Zayenz Lagerkvist <zayenz@gmail.com>"]

[dependencies]
failure = "0.1.1"
structopt = "0.1.0"
structopt-derive = "0.1.0"

[dev-dependencies]
assert_cli = "0.5"
